version: '3.8'
services:
  db:
    image: postgres
    container_name: test-db-img-v1
    environment:
      POSTGRES_USER: parag
      POSTGRES_PASSWORD: Tech8092
      POSTGRES_DB: bajajmall
    ports:
      - "5433:5432"
    volumes:
      - /Users/paragdeshpande2/db-v1:/var/lib/postgresql/data

  app:
    build: .
    image: test-service-img-v1
    container_name: test-service-cont-v1
    depends_on:
      - db
    ports:
        - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bajajmall
      SPRING_DATASOURCE_USERNAME: parag
      SPRING_DATASOURCE_PASSWORD: Tech8092
    restart: always  
    
