pipeline{
    agent any
    stages{
        
        stage("Checkout for git"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/iosdevparag/testspringboot']])
            }
        }
        stage("Building jar"){
            steps{
                sh "cd springboottest; mvn clean install -D skipTests"
                
            }
        }
        stage("Build container and run"){
            steps{
               sh "cd springboottest; docker compose up --build"
            }
        }
    }
}
